export const SEARCH_MOVIE_CATEGORY = 'SEARCH_MOVIE_CATEGORY';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_CATEGORY = 'FETCH_MOVIES_CATEGORY';
export const ADD_LIKE = 'ADD_LIKE';
export const ADD_DISLIKE = 'ADD_DISLIKE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const SEARCH_LOADING = 'SEARCH_LOADING';
export const GET_MOVIES_CATEGORIES = 'GET_MOVIES_CATEGORIES';